import {
  Box,
  Button,
  Flex,
  Heading,
  Image,
  Link,
  List,
  ListIcon,
  ListItem,
  OrderedList,
  Text,
  useColorMode,
} from "@chakra-ui/react";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { forwardRef, useEffect, useState } from "react";
import styles from "../styles/navBar.module.scss";
import { useMediaQuery } from "@mantine/hooks";
import HomeGraph from "../components/HomeGraph";
import { Parallax } from "react-scroll-parallax";
import { CheckCircleIcon } from "@chakra-ui/icons";
import React from "react";
import ReactPlayer from "react-player";
const Home: NextPage = () => {
  const [isPhone, setIsPhone] = useState(false);
  const { colorMode, toggleColorMode } = useColorMode();
  const mq = useMediaQuery("(max-width: 800px)");
  useEffect(() => {
    setIsPhone(mq);
  }, [mq]);
  return (
    <div>
      <Head>
        <title>Join The YOUnion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <HeaderGraphSection />
        <DevicesSection />
        <WithVideoSection />
      </main>
    </div>
  );
};

export default Home;

const GreenButton = forwardRef((props: any, ref: any) => (
  <Button
    ref={ref}
    bg="brand.green"
    color="white"
    _hover={{ bg: "#4cb064" }}
    {...props}
  >
    {props.text}
  </Button>
));

export const MotionGreenButton = motion(GreenButton);

const Header = (props: any) => {
  const [isPhone, setIsPhone] = useState(false);
  const mq = useMediaQuery("(max-width: 800px)");
  useEffect(() => {
    setIsPhone(mq);
  }, [mq]);

  return (
    <Flex
      padding={isPhone ? "30% 5%" : "5% 5%"}
      gap={isPhone ? "25px" : "2%"}
      className={styles.headerContainer}
    >
      <Flex
        padding="0% 0%"
        flexDir="column"
        gap="10"
        justifyContent="center"
        data-aos={isPhone ? "fade-up" : "fade-right"}
        className={styles.headerTitleBox}
      >
        <Heading
          fontSize={isPhone ? "5xl" : "8xl"}
          fontWeight="bold"
          textAlign={isPhone ? "center" : "left"}
          lineHeight="110%"
          fontFamily="Source Sans Pro"
        >
          “The Only Digital Solution That Helps You Fight Back!”
        </Heading>
        <MotionGreenButton
          alignSelf={isPhone ? "center" : "flex-start"}
          text="Join Now"
          size="lg"
          width="fit-content"
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9, backgroundColor: "#4cb064" }}
        />
      </Flex>
      <Flex
        padding="3%"
        paddingRight="0"
        justifyContent="flex-start"
        data-aos={!isPhone ? "fade-left" : "fade-up"}
      >
        <Image src="https://jointheyounion.com/wp-content/uploads/2021/11/tomme-hero-image.png"></Image>
      </Flex>
      {/* {props.isPC ? "PCgkskf" : "933989"} */}
    </Flex>
  );
};

const HeaderGraphSection = () => {
  const [isPhone, setIsPhone] = useState(false);
  const { colorMode, toggleColorMode } = useColorMode();
  const mq = useMediaQuery("(max-width: 800px)");
  useEffect(() => {
    setIsPhone(mq);
  }, [mq]);

  return (
    <Flex
      width="100%"
      bg={colorMode == "dark" ? "#58595B" : "#dedede"}
      height={isPhone ? "1000px" : "500px"}
      flexDir={isPhone ? "column" : "row"}
    >
      <Flex
        flexDir={"column"}
        justifyContent="center"
        alignItems="center"
        width={isPhone ? "100%" : "50%"}
        padding="5%"
        gap={isPhone ? "20px" : "10%"}
      >
        <Heading size="3xl">How YOUnion helps local business</Heading>
        <Text fontSize="2xl">
          Stop paying people you don’t know for services you don’t need. Pocket
          the full sale price with no fees to owners. Own your customers and
          keep them with built in loyalty.
        </Text>
        <Button textAlign="left" variant="ghost" size="lg">
          Learn how you can help your business win
        </Button>
      </Flex>
      <Flex
        width={isPhone ? "100%" : "50%"}
        height={isPhone ? "40%" : "100%"}
        alignItems="center"
        justifyContent="center"
        data-aos={isPhone ? "fade-up" : "fade-left"}
      >
        <HomeGraph></HomeGraph>
      </Flex>
    </Flex>
  );
};

const DevicesSection = () => {
  const [isPhone, setIsPhone] = useState(false);
  const { colorMode, toggleColorMode } = useColorMode();
  const mq = useMediaQuery("(max-width: 800px)");
  useEffect(() => {
    setIsPhone(mq);
  }, [mq]);
  return (
    <Flex
      height="80%"
      width="full"
      padding="5%"
      flexDir={isPhone ? "column-reverse" : "row"}
    >
      <Flex width={isPhone ? "100%" : "50%"} padding="2%">
        <Parallax y={[-20, 20]}>
          <Image src="https://jointheyounion.com/wp-content/uploads/2021/11/prod-shot-food.png"></Image>
        </Parallax>
      </Flex>

      <Flex
        width={isPhone ? "100%" : "50%"}
        padding="5%"
        flexDir="column"
        gap="20px"
      >
        <Heading size="4xl">The New Plan for Local Business</Heading>
        <Text>Your no fee YOUnion membership has benefits:</Text>
        <List spacing={2}>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="brand.green" />
            Reward your loyal customers automatically
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="brand.green" />
            Provide in app ordering and payment
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="brand.green" />
            One touch scheduling, pickup, takeout, and delivery
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="brand.green" />
            Unlimited customer messaging
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="brand.green" />A free,
            integrated POS for cash or cards
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="brand.green" />
            We ONLY support Local Business
          </ListItem>
        </List>
        <MotionGreenButton
          text="Join Now"
          width="20%"
          size="lg"
        ></MotionGreenButton>
      </Flex>
    </Flex>
  );
};

const WithVideoSection = () => {
  const [isPhone, setIsPhone] = useState(false);
  const { colorMode, toggleColorMode } = useColorMode();
  const mq = useMediaQuery("(max-width: 800px)");
  useEffect(() => {
    setIsPhone(mq);
  }, [mq]);
  return (
    <Flex
      height="100%"
      padding="5%"
      bg="brand.green"
      flexDir={isPhone ? "column-reverse" : "row"}
    >
      <Flex
        height="100%"
        width={isPhone ? "100%" : "50%"}
        padding="5%"
        flexDir="column"
        gap="20px"
      >
        <Heading size="4xl">Try going digital at no risk</Heading>
        <OrderedList spacing={2}>
          <ListItem>Reward your loyal customers automatically</ListItem>
          <ListItem>Provide in app ordering and payment</ListItem>
          <ListItem>
            One touch scheduling, pickup, takeout, and delivery
          </ListItem>
          <ListItem>Unlimited customer messaging</ListItem>
          <ListItem>A free, integrated POS for cash or cards</ListItem>
          <ListItem>We ONLY support Local Business</ListItem>
        </OrderedList>
        <MotionGreenButton
          text="Calculate Your Savings"
          width="fit-content"
          size="lg"
          bg="#52bf6d"
        ></MotionGreenButton>
      </Flex>
      <Flex
        height="100%"
        width={isPhone ? "100%" : "50%"}
        paddingTop="8%"
        alignItems="center"
      >
        <ReactPlayer url="https://youtu.be/2qtl8149r3w" controls={true} />
      </Flex>
    </Flex>
  );
};
